### ISSUE TITLE
Potentially merging with `bookmarks.yazi`?

### ISSUE THREAD

**Issue by sxyazi** [DreamMaoMao/bookmarks-persistence.yazi#1]
Hey, thanks for creating this plugin!

I noticed this plugin is quite similar in functionality to the existing `bookmarks.yazi`, with the addition of extra persistence features, so I'm wondering if it's possible to merge it into bookmarks.yazi?

I think @dedukun might be open to accepting the new persistence features, as I found a comment about it https://github.com/dedukun/bookmarks.yazi/issues/6#issuecomment-1992125345.

Or, are there any functionalities that are not the goal of `bookmarks.yazi`, and `bookmarks-persistence.yazi` could target those instead? Clarifying these would be really helpful!

**Comment by dedukun** [comment]
Hey,

Yeah I'm planning of adding persistence to the `bookmarks.yazi` plugin, it's just that I wasn't sure if I would need to do it like it was done here, i.e. writing directly to a file, or if there would be some way of doing it directly via a Yazi API call in some way (I saw that in https://github.com/sxyazi/yazi/pull/826 it had a checkbox for state persistence, and I saw the there's some `state` that is written to a file in the dds).

But if this way is the recommended way of doing it I think that it would be best do define a standard location of storing these files, maybe we should use `PREVIEW.cache_dir` or is the plugin folder a better solution like it was done here?

**Comment by dedukun** [comment]
I saw now that `PREVIEW.cache_dir` is in `tmp` so we shouldn't use that, maybe `BOOT.state_dir`?

**Comment by sxyazi** [comment]
Yeah, ideally the persistent state should be covered through DDS, which is a more efficient way and can broadcast the state in real-time to all Yazi instances. That's also why I didn't add an async file read API, as it's not that efficient.

**Comment by DreamMaoMao** [comment]
At present, a lot of code implementation has a lot of changes, it should not be possible to merge, in addition to the permanent storage of bookmarks feat, there are also support customize the bookmark prompt information and binding keys and automatically generate bookmark information and  automatically generate binding keys

**Comment by DreamMaoMao** [comment]
> Yeah, ideally the persistent state should be covered through DDS, which is a more efficient way and can broadcast the state in real-time to all Yazi instances. That's also why I didn't add an async file read API, as it's not that efficient.

DDS still can keep data after computer reboot?

**Comment by sxyazi** [comment]
Yes, DDS will retain those static messages, that's how it works, https://yazi-rs.github.io/docs/plugins/utils#ps.pub_static

**Comment by dedukun** [comment]
Oh that's already working? I think that I tested `pub_static` when it was first release but I wasn't getting any message when I closed/open Yazi, that's why I hadn't implemented the persistence feature yet. I'll have a look at it again

**Comment by DreamMaoMao** [comment]
It looked a little complicated, like he was preparing it for other scenes. I think it's better to keep the logic of each plugin as independent as possible.
